name: i-summarize
dependencies:
  - python=3.7
  - scikit-learn
  - matplotlib
  - ffmpeg
  - pandas
  - priority
  - beautifulsoup4
  - lxml
  - nltk
  - ipykernel
  - pytorch::pytorch 
  - pytorch::torchvision 
  - conda-forge::umap-learn
  - pip:
    - bert-extractive-summarizer
    - librosa
    - webrtcvad
    - sounddevice
    - inflect
    - PyQt5
    - visdom
    - multiprocess
    - resemblyzer